from utils_module.custom_exception.custom_exception import (
    custom_exception,
    class_custom_exception,
)
